// Puzzles: positions where one move is clearly best, found by
// tools/gen-puzzles.js in games between the AI levels and checked by a deep
// read or an exact solve. [board, side to move, answers, theme, difficulty
// (1 easy, 2 medium, 3 hard), how much the answer gains over the next best
// move (discs), exact, and for an exact one the result with perfect play].
export const PUZZLES = [
  ['----O-------OO----OOOOO--XOXXXX--OOOOO--------------------------', 'O', 'h4', 'mobility', 1, 10, 0],
  ['---OX-----OOOO---XOXXO---OXXXX-----XX-X-----X-------------------', 'X', 'c1', 'mobility', 1, 11, 0],
  ['--------------------X--O---OOXOO--OOOXXX----OOXX---XOX-------X--', 'O', 'h7', 'best', 1, 11, 0],
  ['------------------X-------XXOO--XXXXO---XXOOOO--X--OOX-----XO---', 'X', 'f8', 'quiet', 1, 10, 0],
  ['----O-------OO----OOOOO--XOOOOOO-OOOOO---O-X--------------------', 'X', 'd2', 'best', 1, 20, 0],
  ['--O------XO-------XX-----OOXXOO---OOXO-----OOX-----XOX-------XO-', 'O', 'e8', 'defend', 1, 17, 0],
  ['-----------------OX-X----OXXXO---OXXXO---OOOXO-----XOO---XXXXO--', 'X', 'g8', 'defend', 1, 18, 0],
  ['----------O-------OO----X-OOOO--XOOOOOO-X-XOXO----XOOO--XXXOX---', 'O', 'b6', 'best', 1, 10, 0],
  ['-----X-X-----XXX-OOOOXX---XXXXOO--OOXOOO-OOOOO-X---O--------O---', 'O', 'h3', 'quiet', 1, 22, 0],
  ['--------------------X-XO---XOXXO--XOXOXOOOOOOOOO--XOXO-O-XXXXX--', 'X', 'b5', 'quiet', 1, 11, 0],
  ['-------------------XOOOO-XXOOOO--XOXXXOO-OOOOXXX--OOOOX---OOOO--', 'X', 'c3', 'defend', 1, 11, 0],
  ['--------------OO-OO-OOOX--OOOOXX--OXOXXX--OXXXXX--OXXX-X---XXX--', 'X', 'h1', 'corner', 1, 40, 0],
  ['--XO-O----OOOO--X--OXX--OXOOXX--OOXOXX--OOOXX---O-OXXO----X-O---', 'O', 'a2', 'defend', 1, 27, 0],
  ['--X-O---O-XXXX--OOOOXX--OOOXXX--OOXOXX---OOOOX--X-OOO------O----', 'O', 'f1', 'quiet', 1, 10, 0],
  ['---OOO-----OOO----OOXOOXOOOOOOOOOOXOXXX-OOOOXX------XX------X---', 'X', 'h5', 'quiet', 1, 12, 0],
  ['-------O------OO---X-XOO--XXXXOO-XXXXXOOOXXXOOOOX-OOXO----OOOOO-', 'X', 'a5', 'defend', 1, 10, 0],
  ['--XO-X----OOX---XXOOXXXX-OXOOOXXOOXOOXXX--OXXXXX--O-XX----------', 'X', 'e1', 'quiet', 1, 10, 0],
  ['-------------O--XXXXXXXXXXOOXXXXXOOOOXXXXXOOXXXXXO-XX---OOOO----', 'O', 'a2', 'mobility', 1, 10, 0],
  ['-----O----OXOO--OOXXXOX-XOOXXOO-XXOOXOO-XXXOOOO-X-XXXX----XXXX--', 'X', 'a2', 'defend', 1, 25, 0],
  ['-XX--O----XOOO----OXOOOO--OOXOXO-OOOXOXX-OOXOOXO--XXXO----XXXXO-', 'X', 'h8', 'corner', 1, 12, 0],
  ['--XXXX----OOX---XXOOXXXXXXXOOOXXOOOOOOXX--OOOOXX--OOOO-------O--', 'X', 'a6', 'quiet', 1, 13, 0],
  ['-XXXXXX-O-XOXX--OXXXXX--OOOOXX--OOOOOX--OOOOOO--O-OOOO----XOOO--', 'X', 'g8', 'best', 1, 13, 0],
  ['-----------X-X---XXXXXXX--XOOOOXXXOXXXXXXXXXXXXXXOOXXXX-OOOOOOO-', 'O', 'a4', 'best', 1, 16, 0],
  ['OOO-XXXOOOOOXXX-OOOOXOXXOXOXOO--OXXOOOO-OXXOOOX-OO--O---O-------', 'X', 'd1', 'quiet', 1, 17, 0],
  ['--X-XXXX---XXXXX-OOOOXOX--OOOXOX--OOOOOX--OXOOOX--OXXOOX---XXXXX', 'X', 'c2', 'quiet', 1, 13, 0],
  ['-XXXXX----XOXO--OOOXXXO-O-OXOX-OOOXXXOO-OOXXXO--OOOXXO--XXXXX-O-', 'O', 'b2', 'best', 1, 15, 0],
  ['---O-O--X-OOOO-OXXXOXXOOXOXOXOOOXXOOXXOXXXXOXOX-X-XXXX----XXXX--', 'X', 'h1', 'corner', 1, 12, 1, 2],
  ['----XXX----OOOOOOOOOXXOOOOXXXOOOOOXXXOOO-OXOOOOO--OOOO---OOOOO--', 'X', 'h1', 'corner', 1, 12, 1, 48],
  ['O-O-----OOOOXX-XOXOXOXXXOOXOXXOXOXXXXXOXOOOOXOXX--OOOX-X--OOO---', 'O', 'f8', 'endgame', 1, 8, 1, 6],
  ['--O--X----OOOOOO-OOOOOO-OOOOOOOX---OOXOX-OOOOOOXOXXXXXOXXXXXXXX-', 'X', 'a6', 'pass', 1, 8, 1, 60],
  ['-----X------XX--XXXXXXXOXOOOOOOOXOXOOOOOXXOXOXXOXXXXXXXXOX--XXOO', 'O', 'd8', 'endgame', 1, 12, 1, 50],
  ['OOOOOOOXOOOOOOOXOOXOOX-XOOOOXX-XOOXOX-X-OOXXX---OOX-XO--XOX-----', 'O', 'f8', 'endgame', 1, 16, 1, 52],
  ['OOOOXXX---XXXXX--XXXXXXX-XOXXOX-XXXXOXXXXXOOXX---OOXX----OXXXXX-', 'O', 'h8', 'corner', 1, 12, 1, 52],
  ['--OXOOOO---XOOOO-XXXOOOOXXXXOXOOXXOOXOOOXXXOXXOO----OOOO-----OOO', 'X', 'c7', 'parity', 1, 12, 1, -46],
  ['--XX----OXXXO---XXXOX-OOXOXOOXOO-OOXOOXO-OXOXOOO-OOOOOOO-OOOOOOO', 'X', 'a1', 'corner', 1, 24, 1, -6],
  ['---O-O-XX-OOOO-XXXXOXXOXXOXOXOOXXXOOXXOXXXXOXOOOX-XXXX----XXXX--', 'X', 'h7 g1', 'endgame', 1, 6, 1, 2],
  ['-XXX-X--OXXXXX--OOXOOX--OXOXXXXXOOOOOOOOOXXOOX--OXOOOO---OOOOOO-', 'X', 'g7', 'parity', 1, 10, 1, -44],
  ['XXX-----OX-XX---OOXXXX--OOOXXXX-OOOOXXXXOOOOOXX-OOXXOOOOOOOOOOOO', 'O', 'h6 h3', 'pass', 1, 8, 1, 50],
  ['-------XX-----XXXOX-XXXXXOOXXXXXXOOOXXXXOOXOOXOXOOXOOOOXOOOOOOOX', 'O', 'a1', 'corner', 1, 10, 1, 48],
  ['OXO--X--OXXXXXXXOXOOOXXXOXOOXXOXOXOXOOO-OXXOOOOXOXXOOX------OX--', 'O', 'd1', 'endgame', 1, 10, 1, 22],
  ['--XXXX-X--OOXXXOXXOOXXXOXXXXOXXOXXXOOOOOXXXOXOOO--OOOO-O---OOO--', 'O', 'b7', 'parity', 1, 10, 1, -12],
  ['--OXOOOO---XOOOO-XXXOOOOXXXXOXOOXXOOXOOOXXXOOXOO--XOOOOO-----OOO', 'X', 'e8', 'parity', 1, 12, 1, -46],
  ['-XXXXXX---XOOX-OOOOXXXOOOOOXXXOOOOOXOOOOO-OOXOOO--OOOO-O--OOOOX-', 'X', 'b8', 'defend', 1, 18, 1, 20],
  ['--O--OO-X-OOOOOXXXOOXOOXXOXOOXOXOOOXXOOX-XOXXOOXX-XOOX-X--XXXXX-', 'X', 'a6', 'defend', 1, 14, 1, 28],
  ['--X-XO--OXXXXX-XOXXXXOXXOXOOOXOXOXXOXXOXOXOXXOOXOXXOOO--OXXOO---', 'O', 'a1 g1', 'corner', 1, 32, 1, 8],
  ['--X--O---XOOOO-X-XXOXOXXOXOXOXXXOXOOXXXXOXOOXXXXOOXXXXX-OOOOOOO-', 'O', 'a3', 'endgame', 1, 12, 1, 22],
  ['XXXXXXXOXXXXXXXOXXOXXO-OXXXXXOOOOXXXXO---OXXOO--XOOOOO--XOOOO---', 'X', 'a6 g3', 'pass', 1, 10, 1, 48],
  ['XX--O-OXXXOOOOO-XXOOXXOXXXOXXXOXXXOXOOOXXXOOXOOXX-OOOO--X-X-OO--', 'X', 'b7 f1', 'pass', 1, 8, 1, 58],
  ['X-XXX---XXXXXO--XXXOOOOOXOXOXOOO-OOXXOXO-OXOXOOO-OOOOOOO-OOOOOOO', 'X', 'a5', 'endgame', 1, 8, 1, -2],
  ['O-X-XXX-OOXXXX-XOXOXXOXXOXOOOXOXOXXOXXOXOXOXXOOXOXXOOO--OXXOO---', 'O', 'b1 d1', 'parity', 1, 28, 1, 8],
  ['-OOOOOXOO-OXOXO-OOOOXOO-OOOXOXOOOOXOXXO-OXOOOOO-OXXOO---OOOOOOOO', 'X', 'a1', 'corner', 1, 20, 1, 26],
  ['O-XOXXX-OOOOOX-XOOOOXOXXOXOOOXOXOXXOXXOXOXOXXOOXOXXOOO--OXXOO---', 'X', 'b1', 'parity', 1, 18, 1, -8],
  ['X-XXXO--XXXXOO--XXXOOOOOXXXOXOOOXXXXXOXO-OXOXOOO-OOOOOOO-OOOOOOO', 'X', 'a6', 'parity', 1, 4, 1, 0],
  ['--O--X-X-OOOOOXXXOOXXXXXXOXOXXXXXOXXOXXXXXOXXOXXXOOOOOOXXXXXOO--', 'X', 'g1', 'pass', 1, 12, 1, 48],
  ['-XXXXXXXOXXXXXXX-XOXXXXXXXOOXOXXXXXOOOXXXXXOOOXX--XXXOOX--O-XOOO', 'O', 'd8 a1', 'pass', 1, 12, 1, 2],
  ['-XOOOOXXXXOOOO-XXXXXXXOXXOOXXOOXXXOOXXOXXXXOXOOXX-XXXXOX--XXXX--', 'O', 'g2', 'parity', 1, 16, 1, 16],
  ['OXXOOOOOOXXOOX-XOXOXXOXXOXOOXXOXOXXOXXOXOXOXXOOXOXXOOO--OXXOO---', 'X', 'g2', 'parity', 1, 8, 1, -8],
  ['OOO-----OOXOO-XOOOOOOOXOOOOOOOXOOOOOOOXOOOOOOOXOOOOOOOOOOOOOOOOO', 'O', 'd1 g1', 'pass', 1, 10, 1, 64],
  ['OOOOOOOXOOOOOOOXOOXOOOOXOOOXXXXXOOOOX-X-OOOOXX--OOOOXX--XOOOOOOO', 'O', 'g7', 'endgame', 1, 8, 1, 54],
  ['XXXXXXXOOXXXXXXOOXXXOOXOOXXXOXOOOXOXOXOOOXXOOOXOO-OOOX--OO-OOO--', 'X', 'g7', 'endgame', 1, 8, 1, 0],
  ['--------------------------XXX-----XXXXXX--OXOX-----XXO----OX-O--', 'O', 'e8', 'quiet', 2, 12, 0],
  ['---O-------OOO----OOOOO---OOOOX---OOOO----OO-O-----O------------', 'X', 'b4', 'best', 2, 21, 0],
  ['---OOX----OOOO----OXOOO---XXOO---XXXX-----X--X------------------', 'X', 'c1', 'best', 2, 10, 0],
  ['--------------------O----OOOO---OOOOXX--XXXXOOO-XXXX-O--X-------', 'X', 'e7', 'quiet', 2, 20, 0],
  ['---X------X-----XXOOOOO-XXOXOOO-XXOOOOO-XX----------------------', 'O', 'b1', 'mobility', 2, 32, 0],
  ['--------------------------XXX----OXXXXXX-XOOOOOO--OOXO----OOOOO-', 'X', 'h7', 'quiet', 2, 12, 0],
  ['------------O-----XOOO---OOOOOO--OOXO-O---OOXXX-----XX-----XXXX-', 'O', 'h6', 'best', 2, 11, 0],
  ['-------------------------OXXX----XOXXXXXXXXOXXXX--XOOO----OOOO--', 'O', 'b8', 'quiet', 2, 12, 0],
  ['-----------XXO-----XXOXX---XXXX----XXOXO--OXOOOO--OOXO-O--O-X---', 'X', 'f8', 'quiet', 2, 11, 0],
  ['--O-XX-----XXXX--OOOOOO--XOOXOO--XXXOOX---XOO------O-X----------', 'X', 'h5', 'defend', 2, 10, 0],
  ['------------XX---XOOOO--OXXXOO---XOOOO--XXOOO----OOOO---OX-O----', 'X', 'c8', 'quiet', 2, 16, 0],
  ['--OX------XXXO-----XOXXXXXXXXOX--XXXXXX---XXXX-X---X-------X----', 'O', 'e1', 'quiet', 2, 19, 0],
  ['-OOO-X-----XOO---XXXXOOO--XXXXOO--XXXXXO-X-XXXX------X----------', 'X', 'g1', 'quiet', 2, 23, 0],
  ['---------------O----X-OO---XOOXO-XXOOOXOOOXOOOOO--XXXO-O-XXXXX--', 'X', 'f3', 'best', 2, 11, 0],
  ['--O-O-X--XXXXX---XXXXXXX-XOXXXX-OXXOXXX--XXXOXO------O----------', 'O', 'd1', 'quiet', 2, 13, 0],
  ['----X--X-----XXX-OO-OOXX--OOXOXX--OXOXXX--OXXXXX--OXXX-X---XXX--', 'O', 'g8', 'quiet', 2, 19, 0],
  ['--X------OXXO---XOXXOO--XXXXOO--XOXXOOO-XXOXOO--X-XX-O----OXO---', 'O', 'b1', 'best', 2, 19, 0],
  ['--------X-XXXX--XXOOOOO-XXXOOXOO-XXXXOO--XXXOOO----XXO----OXXO--', 'O', 'c7', 'best', 2, 11, 0],
  ['-OX------OOXO---XOXOOO--XXXXOO--XOXXOOO-XOOXOO--XOXX-O----OXXX--', 'X', 'a8', 'corner', 2, 28, 0],
  ['--O--X----OOOOOX-OOOOOXXXXOOOXOX--OOXOO--O-XOOOXO-X-OX------OX--', 'X', 'a3', 'quiet', 2, 11, 0],
  ['OX--XO-OOOXXXOO-OOOOOOXXXXXOOO---XXOOOO-OXXXXXX-XO--------------', 'O', 'a8', 'corner', 2, 22, 0],
  ['--OXX-----OXXX-XX-OXOXXXX-OXOOXXXOOXOOOXXOOOOXOX--OOOO------O---', 'O', 'f1', 'best', 2, 10, 0],
  ['----O------OOO----O-OXOOXO-XOXXOX-OXXOXOXXXOOXXOXXXXXXX--OOOOOO-', 'X', 'd3', 'defend', 2, 12, 0],
  ['--OOOO--XXXOXX---XXXXX-XOOOOXXX--XXXOXOOXXXOOOOO--XXOX----XXXXX-', 'O', 'a1', 'corner', 2, 17, 0],
  ['OOOO-----OOXXX-O-XOOXXOO--OXOOOO-XXOOOOO-XXOXXOO--OOOOX--O-OOOOX', 'X', 'a2', 'endgame', 2, 6, 1, 2],
  ['XXXXO---XOXXOO--XXOXXO--XOXXXX--XOOXOXOOXOXXXXOOXOOOXX--XO-O----', 'X', 'e8', 'endgame', 2, 12, 1, 44],
  ['--XXX-----XXXX---OXXXXX-OOXXXXXXOOOXOOXOOOOOXXOXO-OOXX---XXXXXX-', 'X', 'a2', 'parity', 2, 8, 1, -12],
  ['--OOOOOO-XXOOXOX-XOXOOOXXXXXXOOXXXXOOXXXX-XXOOX---XOXX----XO-X--', 'O', 'h6', 'parity', 2, 10, 1, 52],
  ['--XXX-O---OXOO--OOXOOOOOOXOOOXO-OOXXOOO-OXOXXOO-X-OOOXO---OOOOXO', 'O', 'a8', 'corner', 2, 12, 1, 0],
  ['--XOO-----XOOO--OXOOXOOOXOXOXXXOOOOXOXXO-OOOXOXO--OOOXXO--OOOOXO', 'X', 'f1', 'parity', 2, 8, 1, 18],
  ['--OXOOOO--OOOOOOX-OXOOOOOOOOOOOOOOXOOOO--OXOOOOOO-OOOO---OXXX---', 'X', 'a8', 'corner', 2, 10, 1, 28],
  ['-XXXXXXXOOOOOOX-OOOXXXXXOOXXXXXXOOXXOOOX-XOOOOOXXXOO------O-----', 'X', 'a6', 'parity', 2, 16, 1, 22],
  ['-X-O-O-XX-XOOO-XXXXXXXOXXOXOXOOXXXOOXXOXXXXOXOOOX-XXXX----XXXX--', 'O', 'c1', 'parity', 2, 14, 1, 12],
  ['-OO-XX-O--OXXXXX-OXOXXXXOOOXXOOXOOXXOXOXOOOXOXO-XX-XXOX---XXO--X', 'O', 'a8', 'corner', 2, 14, 1, 36],
  ['--OO----X-OO-XOO-XXXXXOXOOXOOXOOXOXXOXOOXXOOXOO-XXXXX-O-XOXXXX-O', 'O', 'a3', 'endgame', 2, 10, 1, -2],
  ['----XXXOX-XXXXXXXXXXXOX-XXXXOXOXXXXOOXOOXXOOOOOOX-XOOX----XOXX--', 'O', 'h3', 'parity', 2, 10, 1, 28],
  ['O--OOOO-XOOOOO-OOOOOOOOOOOOOOOXOOOOOOOXOOOOOXXOO-OOX---O-XXO----', 'O', 'a8', 'corner', 2, 24, 1, 8],
  ['--XXXXOX--OOXXOOXXOOXXOOXXXXOXOOXXXOOOOOXXXOXOOO--OOOO-O---OOO--', 'X', 'b8', 'parity', 2, 10, 1, 22],
  ['--XXXX----XOOOO-OXOXXOOOXOXOOXXOOOOOOXXO-OOOXOXO--OOOXXO--OOOOXO', 'X', 'a7', 'parity', 2, 8, 1, 18],
  ['OX-X-X--OXXXXX--OXOXOXXXOOOXXOOOOXOOXXO-OXOOOXO-O-OOOO--OOOOOOO-', 'X', 'b7', 'parity', 2, 12, 1, -38],
  ['OXOOOO--OOXOXX--OOOXXX-XOOOOXXXX-XXXOXXXXXXOOOXX--XXXXXX--XXXXX-', 'O', 'h8', 'corner', 2, 8, 1, 58],
  ['OXOOOOOO-XXOXX---XOXOXXOXOXXXOOOXXOOXXOOXOOOOOOO--XXXX-X--XXXX--', 'O', 'h2', 'endgame', 2, 8, 1, 44],
  ['-XXXXX---OOOX---OOOXXXXXOOOOXOXXOOOXOXXXOOXXXOXOOXXXOOO---XXXXX-', 'O', 'h2', 'parity', 2, 14, 1, 22],
  ['OOOOXXXXOOOOOXXX-OOXOOOX-OOXXXOX--OOXXOX--OXOXXX--XXXOXX-X-XXXXX', 'X', 'a5 b7', 'endgame', 2, 4, 1, 2],
  ['--XXXX-OOOXXXXOOOOXXXOXOOXOOOXOOXXOOXOOOXXOOOO-OXXOOOO----OXXO--', 'X', 'b1 g1', 'endgame', 2, 8, 1, -6],
  ['XXXXXXXXXXXXXXO-XXXXXX--XOXXXXX-XOOOXOO-XOOXOXO-OOOOOOOO--OXXO--', 'O', 'h4', 'endgame', 2, 12, 1, -36],
  ['O-XXXXXXO-XOOXXXOOXOOOXX-OXOXOOXOOXXXOOOOOXXXOO--XXXOO---OOOOO--', 'X', 'a4', 'parity', 2, 10, 1, 20],
  ['O-OOOO---OXOOO--XXOXOOO-XXXXOOOOOXOXXOOOOOOOOXOOO-OOOOOO-OOO-XXX', 'X', 'a2', 'endgame', 2, 10, 1, 30],
  ['OOOOOO--OOXXXXX--XOXOXX-XXOOXOXXXXXXOXXXXXXXXOXXXXOOOXX---OOOOX-', 'O', 'g1', 'endgame', 2, 10, 1, 46],
  ['XXXXXXXXXXXXXXX-XXXXXXXOXXXXOOOOXXXXXOXOXXXXXOOO--XXX--O--XXXX--', 'O', 'b8', 'endgame', 2, 22, 1, -24],
  ['XXOOOOO-OXXOOO-OOXXXXXOOOXOOXOOOOXXXXXOOOOXXXOO--OOOOX---XXXXXX-', 'X', 'a7', 'pass', 2, 34, 1, 62],
  ['XXXXXX-OOXXXXXOOOXXXOOXOOXXXOXOOOXOXOXOOOXXOXXXOO-OO-X--OO-OOO--', 'X', 'g1', 'parity', 2, 12, 1, 0],
  ['-X--OX--OXXO-XOOOXXXXOOXOXOXOOXXOXOOOOXXOXOOXXOXOOXXXX-XOOOOOO-X', 'X', 'h1', 'corner', 2, 8, 1, -8],
  ['XOOOOOOOXOOXXOOOXOXOOOOOXXXOOOXXXXXOOOX-XXXXXXX-XXXXX-XO--XXX---', 'O', 'h8', 'corner', 2, 10, 1, 26],
  ['-OOOOX----OXXX-XOOOXXXOXOOXXXXXXOXOXOOXXOOXOOOXXOXOXXXXX-OOOOOOO', 'O', 'g1', 'defend', 2, 10, 1, 20],
  ['--OOOOOOO-OOXXOOOOOXOOOOOOOXOOOOXXXOOOOOXXOXXXXO-OXOXXXO-XXXXX--', 'O', 'h8', 'corner', 2, 16, 1, 26],
  ['--XOOOOOOXXXOOOXOOXOOOOXOOOOXXOXOOOXXOOXOOXXXXXXOX---XX-XO-OOOOX', 'O', 'a1', 'corner', 2, 8, 1, 40],
  ['-OOOOOO---XXOO-X-XXXXOXXXXXOXXOXXOOOXXOXXOOOOXOXXXXXXOOXX-XXXXOX', 'O', 'a3 b8', 'endgame', 2, 12, 1, 14],
  ['-XXXXX--X-XXXX-OXXXOXXXXXXXOXOXXOXXOOXXXOXOOXXXXOOOOXXX-OOOOOOOO', 'O', 'h7', 'pass', 2, 12, 1, 56],
  ['XOOOOOOOXOOXXOOOXOXOOOOOXXXOOOXXXXXOOOX-XXXXXOX-XXXXX-XO--XXX-XO', 'O', 'f8', 'pass', 2, 8, 1, 26],
  ['------------O-----XOOO---OOOOOO--OOXO-O---OOXXX-----OX------XXX-', 'X', 'h4', 'quiet', 3, 10, 0],
  ['--X--X-----XXX-X---XXXX----XXXOO---XXXOO--XXXOOO----OO-O----O---', 'X', 'g7', 'mobility', 3, 13, 0],
  ['----O------XOO--XXXXOOO-XXOOOXOOXOXXOOO--OOXO-O---OOO-----O-----', 'O', 'd1', 'quiet', 3, 12, 0],
  ['-XXXXX--O-XOXX-O-OOXOXOO-OOXOOOO-OOXOXOO--OOOOOO--O-------------', 'O', 'g1', 'quiet', 3, 12, 0],
  ['----------X----X--XXXXOX-X-XXXXX-OXXXXXX-XOXOXX--XXOXXO---XOOOOX', 'O', 'a6 a8', 'quiet', 3, 13, 0],
  ['---------------X----O--X---OOOOXOOOOOOOXOOOXXOOXOOOOOOO-OXXXXXXX', 'X', 'a4', 'quiet', 3, 16, 0],
  ['---X----OOXXXX--OOOXXXO-OOXOOOO-OOXOOOO--XXOOOO-X-XXXX----X-----', 'X', 'h6', 'quiet', 3, 10, 0],
  ['--OOO-----OOOX---OOXOX---OOOOXXXX-OXOXX--OOOXXXXO-XXOX---XX-O-X-', 'O', 'g7', 'quiet', 3, 19, 0],
  ['-XX-OOOXO-XOOOX-XOXXXXXX-OOXXXXX-OOOXX-X--OOOOOX--OO------O-----', 'X', 'a1', 'corner', 3, 21, 0],
  ['--X------OXX-X---OOXXX--XOXOXXXX-OXXOXXXOOOOOOXX--OOOO-X--OOOO--', 'X', 'b7', 'quiet', 3, 10, 0],
  ['--X--X---OXXXX--OOOXXX--OXXOXX--OXOXOXO-OXXXOOOOOXXXOO-X--O-XO--', 'X', 'g7', 'quiet', 3, 12, 0],
  ['XXXXX-----OOXXXX-OOOXOXOOOOOXXOOOOOOXOO-OOXOOOO-O-OOOO-----O----', 'X', 'b8', 'quiet', 3, 10, 0],
  ['---XXX-----OXXXO--OXOXXO-OOOXOXOOOOXOOOO-OXOXOX-O-XXOXXX--XXXXXX', 'X', 'c2', 'parity', 3, 8, 1, 14],
  ['--OXOOOO--OOOOOOX-OXOOOOOOOOOOOOOOXOXOO--OXXOOOOO-XOOO----XXX---', 'O', 'b7', 'endgame', 3, 8, 1, -20],
  ['--OOOO---XOOOO-O-XXOXXOOXXOXOOXOXXOXXOXOXXOOXXX-X-OOOOX----OOO--', 'O', 'a3', 'endgame', 3, 12, 1, 2],
  ['--XXXX----OOXXOOXXOOXXXOXXXXOXXOXXXOOOOOXXXOXOOO--OOOO-O---OOO--', 'X', 'b8', 'parity', 3, 12, 1, 24],
  ['OOOO----XXXXXX-O-XOOXXOO--OXOOOO-XXOOOOO-XXOXXOO--OOOOOO-O-OOOOX', 'X', 'h1', 'corner', 3, 4, 1, 2],
  ['--XXXX---OXXXX--OXXXXOOOOXXOOOOOXXOXXOOOXXOOOO-OXXOOOO----OXXO--', 'X', 'a2', 'parity', 3, 4, 1, 0],
  ['--XXX-O---OXOO--OOXOOOOOOXOOOXO-OOXXOOO-OXOXXOO-O-OOOXO-O-OOOOXO', 'X', 'a2', 'endgame', 3, 2, 1, 0],
  ['XXXXXXX-XOOXXOO-XOXOXX-OXXOOXXO-XXXOOO--XXOOOO---XXOXO----OOOOO-', 'X', 'g3', 'parity', 3, 12, 1, 24],
  ['-XXXOOOO--XOOOOOX-OXOOOOOOOOOOOOOOXOOOO--OXOOOOOO-OOOO---OXXX---', 'O', 'f8', 'defend', 3, 8, 1, 8],
  ['--XXXX--X-XOXX-OXXXXOXOOXXXXOXOO-XXXOXOOOOOXXOOO--OOOOO---OOOOOO', 'X', 'b8', 'endgame', 3, 10, 1, 4],
  ['-OOOO-X-X-OOOX--XXOOOO--XXOXOOOXXXXXOOOXXXOXOXOXX-XOXX-X-XXXXXX-', 'X', 'g3', 'endgame', 3, 14, 1, 26],
  ['OXXOOOOXOOOOOOOXOXOXXXX-OOOOXXOOOOOOOOO--OXOXOOX--OOOO-----OOO--', 'X', 'a6', 'endgame', 3, 2, 1, 0],
  ['---XXXXOO-XXXXOOOOXXXOOOOXOXOXOO-XXOOOXOXXXXXXOO--XOXX-O-XXXXX--', 'O', 'g7', 'parity', 3, 8, 1, 44],
  ['-OOOO-X---OOXOOXXXXXXOOXOXXOOXOXOOXOOXOXOOOXXOOX--XXOOO---XXXXX-', 'O', 'a2', 'parity', 3, 28, 1, 18],
  ['---OOOOOO-X-XXXOO-XXXXXXOXXOOXXXOXXOXOXXOOXXXOOOO-XOOX---XXOXXX-', 'O', 'b3', 'endgame', 3, 8, 1, 44],
  ['XOOOOO--OOOOOOX--OXOOOX--OXXOOXXOOXXXOXOOOXOXXOO-XXXXX-OXXXXXX--', 'X', 'h8', 'corner', 3, 12, 1, 28],
  ['XXXXXX--OXXXXXXXOXXXOOXXOXXXOOOXOXOXOOOXOXXOOOOOO-OO----OO-OOO--', 'X', 'h7', 'endgame', 3, 2, 1, 0],
  ['OO--XXOO-OOXXXXOOOOOOXXO-OOOXOOO-OOXOOOOOOXXOOOO-XXXOO---XXXXXX-', 'X', 'c1', 'endgame', 3, 10, 1, -2],
  ['-OOOOOO--OOOOOO--OOOOXOO-OOOOXOOXOOOOXXO-OXOXXXX-OXXXXXX-OXXXXXX', 'X', 'a4', 'endgame', 3, 10, 1, 50],
  ['XOOOOO-XXXOOOOXXXOXOOXXXOOOXXOXXXXXXOOX--XXXXOXO---XXXXO---XOXXO', 'O', 'c7', 'parity', 3, 12, 1, 10],
  ['OXXXXXXXOXOOXO--OOOXXOO-OXOXXO--OXXOXOO-OXOOOOOOXXXXXO--OOOOOOOO', 'X', 'h5', 'endgame', 3, 8, 1, 16],
  ['-XOOOOOXOXXXXOOOOXXXOXOXOXOXXOXXOXOXXXXXOOXOXXXXO-OXXX---OOOX-O-', 'O', 'f8', 'defend', 3, 8, 1, 18],
  ['XOOOOOOOXOOOOOOOXOOOXOXOXXXXOXOO-XXOOOXOXX-XOOXO--XXXXOO--O-XOOO', 'O', 'c6', 'parity', 3, 8, 1, 40],
  ['OOOOOOX--OOOOX-OXXOOXXXOXOXOOXXOOOOOOOXO-OOXXOOOO-XOOOOO-XXXXXX-', 'O', 'g2', 'endgame', 3, 8, 1, 32],
];
